# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu-14.04-amd64-vbox"
  config.vm.box_url = "https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vbox.box"

  config.vm.network "private_network", ip: "192.168.40.40"

  config.vm.synced_folder "../", "/srv/graduates"


  # Provisioning scripts
  config.vm.provision "shell", inline: "apt-get update"
  # config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  # General project setup
  config.vm.provision :shell, path: "provisioning/venv/venv.sh"
  config.vm.provision :shell, path: "provisioning/graduates/project.sh"
end
